### ISSUE TITLE
Magento 2.2.5

### ISSUE THREAD

**Issue by elucidsoft** [springbot/magento2-plugin#33]
We are in the process of upgrading our Magento servers to 2.2.5 and we need to know when you are expected to support this release? This would help us plan accordingly.  Can you please provide me with a date that you plan to have support for Magento 2.2.5?

**Comment by JoeyK4816** [comment]
Hi @elucidsoft we should be compatible with version 2.2.5. Have you attempted installing? If you have any issues, please let us know.

**Comment by JoeyK4816** [comment]
Closing for now. If you have any additional questions, please contact us at Support@Springbot.com
