### ISSUE TITLE
Making the admin grid column float right

### ISSUE THREAD

**Issue by MrLuisAmador** [springbot/magento2-plugin#47]
It seems your latest update is causing every page within the admin to float right.

![screen shot 2018-10-02 at 11 13 09 am](https://user-images.githubusercontent.com/6766589/46358283-b4e05580-c634-11e8-84fb-4f9066ea5a2c.png)

If you look, you can see that you adding a class, admin-2columns-left, that is being applied globally.

![screen shot 2018-10-02 at 11 06 18 am](https://user-images.githubusercontent.com/6766589/46358382-e1946d00-c634-11e8-8831-cb8c5e8eeb59.png)

I have found it in this file:

![screen shot 2018-10-02 at 11 08 53 am](https://user-images.githubusercontent.com/6766589/46358461-04268600-c635-11e8-814b-58f593fda57c.png)

Can you please fix this issue?

**Comment by JoeyK4816** [comment]
Pull request has been approved and merged. Thank you for the report and contribution.
