### ISSUE TITLE
attribute test

### ISSUE THREAD

**Issue by mattyl** [springbot/magento2-plugin#77]
we are getting hundreds of these messages

main.ERROR: failed getting attribute test. source_model: Magento\Eav\Model\Entity\Attribute\Source\Table. error:Call to a member function getId() on null []

we think its springbot plugin that is causing it

does anyone agree? any idea for a solution

**Comment by JoshLucio** [comment]
We have seen this error on stores that migrated. It was caused by the springbot_queue table containing items that could not be processed. Clearing the table solved the issue.

**Comment by mattyl** [comment]
creating an atrtibute called test resolved the issue
